### ISSUE TITLE
Doesn't work with new React builds

### ISSUE THREAD

**Issue by halt-hammerzeit** [kodyl/react-document-meta#3]
```sh
G:\work\cinema [master +0 ~5 -0]> npm install --save react@0.14.0-rc1
npm WARN package.json cinema@1.0.0 license should be a valid SPDX license expression
npm WARN unmet dependency G:\work\cinema\node_modules\react-intl requires react@'>=0.11.2 <1.0.0' but will load
npm WARN unmet dependency G:\work\cinema\node_modules\react,
npm WARN unmet dependency which is version 0.14.0-rc1
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "--save" "react@0.14.0-rc1"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-document-meta@1.0.1 wants react@>= 0.13.0
```

A fix I can suggest: remove peerDependencies.

**Comment by danieljuhl** [comment]
I'll have a look at this...

**Comment by halt-hammerzeit** [comment]
While you are upgrading your module to React 0.14.0-rc1, also fix this error:
```
[1] Error: Cannot find module 'react/lib/ExecutionEnvironment'
[1]     at Function.Module._resolveFilename (module.js:336:15)
[1]     at Function.Module._load (module.js:278:25)
[1]     at Module.require (module.js:365:17)
[1]     at require (module.js:384:17)
[1]     at Object.<anonymous> (G:\work\cinema\node_modules\react-document-meta\dist\index.js:19:37)
```

**Comment by halt-hammerzeit** [comment]
FYI
https://github.com/nikgraf/belle/pull/178

```ExecutionEnvironment is not part of React's public API, and depending on it will break in 0.14```

**Comment by danieljuhl** [comment]
A new release is planned for tomorrow, which should fix all of this.

**Comment by halt-hammerzeit** [comment]
Oh, that's good, closing this for now.

**Comment by danieljuhl** [comment]
I'll keep it open, until the release has landed.

**Comment by danieljuhl** [comment]
As this breaks React v0.13.x you should upgrade to `react-document-meta@2.0.0-rc2`
